// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2NsTbLeap4wrzUarAW2pQYf3YaStYPqo',
    appId: '1:953282742732:web:874ad2ba31236d123b3569',
    messagingSenderId: '953282742732',
    projectId: 'testpoint-81a9a',
    authDomain: 'testpoint-81a9a.firebaseapp.com',
    storageBucket: 'testpoint-81a9a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2NsTbLeap4wrzUarAW2pQYf3YaStYPqo',
    appId: '1:953282742732:android:874ad2ba31236d123b3569',
    messagingSenderId: '953282742732',
    projectId: 'testpoint-81a9a',
    authDomain: 'testpoint-81a9a.firebaseapp.com',
    storageBucket: 'testpoint-81a9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2NsTbLeap4wrzUarAW2pQYf3YaStYPqo',
    appId: '1:953282742732:ios:874ad2ba31236d123b3569',
    messagingSenderId: '953282742732',
    projectId: 'testpoint-81a9a',
    authDomain: 'testpoint-81a9a.firebaseapp.com',
    storageBucket: 'testpoint-81a9a.firebasestorage.app',
    iosBundleId: 'com.example.testpoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2NsTbLeap4wrzUarAW2pQYf3YaStYPqo',
    appId: '1:953282742732:macos:874ad2ba31236d123b3569',
    messagingSenderId: '953282742732',
    projectId: 'testpoint-81a9a',
    authDomain: 'testpoint-81a9a.firebaseapp.com',
    storageBucket: 'testpoint-81a9a.firebasestorage.app',
    iosBundleId: 'com.example.testpoint',
  );
}